version: '3'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    restart: always
  app:
    build: .
    image: test123
    command: python -u chat.py
    ports:
      - 5000:5000
    env_file:
      - bot/.env
    depends_on:
      - mongodb_container
    restart: always

