version: "3"
services:
  mongo:
    container_name: docker-mongo
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: organization
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    # всегда изменять порт на 27019, т.к невозможно подключиться
    ports:
      - "27019:27017"
  express:
    container_name: docker-mongo-express
    image: mongo-express
    ports:
      - "9001:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongo

  app:
    container_name: docker-chat-bot
    build: .
    command: python -u chat.py
    ports:
      - 5000:5000
    env_file:
      - bot/.env
    depends_on:
      - mongo
    links:
      - mongo
    restart: always

